(project):
    # a central place for filepaths
    (path_to):
        this_file: "./info.yaml"
        hyperparams_folder: "./hyp_opt"
        ac3_start: ./examples/atari/reproduction/a3c/train_a3c.py

    # git-ignored path (chooses profile)
    (local_data): ./local_data.ignore.yaml

    (profiles):
        (default):
            verbose: True
            number_of_processes: 10
            number_of_malicious_processes: 3
            banning_method: 'softmax' # 'softmax' or 'permaban'
            attack_method: 'sign' # 'sign', 'act', or 'noise'
                                  # 'sign' being the reverse of a good agent (* 2.5)
                                  # 'act' being from a random policy (very dumb agent, but gradient in correct direction)
                                  # 'noise' being simply return noise instead of a gradient
            random_seeds: [ 0 ]
            
        CARTPOLE:
            env_config:
                env_name: CartPole-v1
                number_of_timesteps: 100_000
                learning_rate: 0.001
                beta: 0.00002
                t_max: 5
                activation: 1
                hidden_size: 64
                permaban_threshold: 500
                variance_scaling_factor: 1
        CHEETAH:
            verbose: False
            env_config:
                env_name: "HalfCheetah-v2"
                number_of_timesteps: 100_000
                learning_rate: 0.00003
                beta: 0.0000003
                t_max: 3
                activation: 1
                hidden_size: 2
                variance_scaling_factor: 1 #FIXME: not optimized at all
                permaban_threshold: 500    #FIXME: not optimized at all
        LUNAR_LANDER:
            env_config:
                env_name: "LunarLander-v2"
                number_of_timesteps: 100_000