#!/usr/bin/env -S deno run --allow-all

import { FileSystem } from "https://deno.land/x/quickr@0.5.0/main/file_system.js"
import { run, throwIfFails, zipInto, mergeInto, returnAsString, Timeout, Env, Cwd, Stdin, Stdout, Stderr, Out, Overwrite, AppendTo } from "https://deno.land/x/quickr@0.5.0/main/run.js"


const fileInfo = await FileSystem.info(Deno.args[0])
if (!fileInfo.exists) {
    throw Error(`That file doesn't seem to exist: ${fileInfo.path}`)
}

// convert hyperopts
var { success } = await run`commands/project/convert_optuna_log ${fileInfo.path}`
console.log(`success is:`,success)
// convert curves
var { success } = await run`commands/project/convert_curve_log ${fileInfo.path}`
console.log(`success is:`,success)
// plot curves
const [ folders, name, ext ] = FileSystem.pathPieces(fileInfo.path)
var { success } = await run`python3 ./hyp_opt/curve_plotter.py ${FileSystem.join(...folders, name+".curves.json")}`
console.log(`success is:`,success)