#!/usr/bin/env -S deno run --allow-all

import { FileSystem } from "https://deno.land/x/quickr@0.5.0/main/file_system.js"
import { run, throwIfFails, zipInto, mergeInto, returnAsString, Timeout, Env, Cwd, Stdin, Stdout, Stderr, Out, Overwrite, AppendTo } from "https://deno.land/x/quickr@0.5.0/main/run.js"

const oneHourInMs = 1000 * 60 * 60
const task = async ()=>{
    // push
    if (success) { var { success } = await run`git add -A` }
    if (success) { var { success } = await run`git commit -m ${'- autolog'}` }
    if (success) { var { success } = await run`git push` }
}
setInterval(task, oneHourInMs)
task()